### ISSUE TITLE
Cannot read/write image in a folder with cyrillic name, on windows

### ISSUE THREAD

**Issue by Fedik** [LeoHsiao1/pyexiv2#21]
The library cannot read/write the image from folder that contain cyrillic symbols, on windows, however on Linux it works very well.

Example little thing:
```python
# read
image_path = "C:\Users\TheUser\Desktop\test\тест призначення\electromecánico\good bike.JPG"
img = pyexiv2.Image(image_path)
metadata = img.read_xmp()
print(metadata)

# write
keywords = ["foo", "bar"]
new_meta = {'Xmp.dc.subject': keywords}
img.modify_xmp(new_meta)
```

Produce error `Failed to open the data source: No such file or directory (errno = 2)`

Traceback:
```
Traceback (most recent call last):
  File "C:\py-dev\test-meta\edit-xmp.py", line 15
    img = pyexiv2.Image(image_path)
  File "C:\py-dev\test-meta\env\lib\site-packages\pyexiv2\core.py", line 16, in __init__
    self.img = api.open_image(filename.encode(encoding))
RuntimeError: C:\Users\TheUser\Desktop\test\тест призначення\electromecánico\good bike.JPG: Failed to open the data source: No such file or directory (errno = 2)
```

`api.open_image()` does not see the file in some reason.
If use path without cyrillic symbols then all works.

**Comment by LeoHsiao1** [comment]
This error, `No such file or directory` , is usually reported for the following reasons:
- The image path does not exist.
- The image path could not be decoded correctly.

What you're dealing with is obviously the second case.

Most of the functions provided by pyexiv2 include a default parameter: `encoding='utf-8'`
If you encounter an error because the data contains non-ascii code characters, please try to change the encoding parameter. For example:
```py
img = pyexiv2.Image(image_path, encoding='utf-8')
img = pyexiv2.Image(image_path, encoding='ISO 8859-5')
```

In addition, the default encoding for your Windows system may not be utf-8, so you cannot decode in utf-8.

**Comment by Fedik** [comment]
> What you're dealing with is obviously the second case.

yeah, I suspect it, but not get why :wink: 
because 
```python
file = open(image_path, "r")
```
works very well, without any encoding.

Is there a way to give the `file object` to `pyexiv2.Image` instance? this could be as work around.

> In addition, the default encoding for your Windows system may not be utf-8, so you cannot decode in utf-8.

That also an idea, I will try [locale.getpreferredencoding()](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) , will see what it will do, and will write you back.

**Comment by LeoHsiao1** [comment]
In fact, pyexiv2 calls the C++ API of exiv2. Therefore, only one string representing the path of the file can be passed.
Only with the correct encoding can the string be successfully identified.

**Comment by LeoHsiao1** [comment]
As far as I know, executing `chcp` in Windows CMD will display a number,  which represents some kind of encoding format.
As for Python's built-in function `open()`, it might guess the encoding format automatically.
The Python3 interpreter supports Unicode characters very well, but C++ can only recognize ASCII code characters after encoding.

**Comment by LeoHsiao1** [comment]
The default encoding format in Linux system is utf-8, so you can use utf-8 to decode file paths.
```sh
leo@Leo:~$ echo $LANG
C.UTF-8
```

**Comment by Fedik** [comment]
hm, with `os.path.exists(path.encode('utf-8'))` it say `True`.

I tried default encoding cp1252 but it not able to encode cyrillic, and if use cp1251 then it able to encode cyrillic but pyexiv2.Image stlll fail with exception.

well, okay

**Comment by Fedik** [comment]
@LeoHsiao1 one more question

Does it possible to implement this method [static Image::AutoPtr open (const byte *data, long size)](https://www.exiv2.org/doc/classExiv2_1_1ImageFactory.html#a8692f9f2ec13b2e8df084b8a2156db78) ?
To load the image binary data.

So I can do:
```python
the_file = open("in-file", "rb") 
data = the_file.read()

img = pyexiv2.Image(binary_data = data)
```

I think that would be nice feature.

**Comment by LeoHsiao1** [comment]
It looks like it can be done, and I'll try to do it in the next week.

**Comment by LeoHsiao1** [comment]
I've implemented this method and will release a new version in a few days.

**Comment by LeoHsiao1** [comment]
Finally, I released [v2.3.0](https://github.com/LeoHsiao1/pyexiv2/releases/tag/v2.3.0).
Add class [ImageData](https://github.com/LeoHsiao1/pyexiv2/blob/v2.3.0/docs/Tutorial.md#class-imagedata). It is used to open an image from bytes data.
I ran into some bugs when transferring  bytes data, which caused me to take a week longer than I expected.

**Comment by Fedik** [comment]
@LeoHsiao1 thanks! works very well, I just tested

**Comment by kolt54321** [comment]
Hi @LeoHsiao1 ! I'm having a bit of trouble following how to use the new class to solve cyrillic/other non-ascii names. The code right now looks like this:

```
from pyexiv2 import Image as TaggedImage
xmp_file_obj = TaggedImage(final_image_filename) # Image exists but with non-ascii letters
xmp_file_obj.modify_xmp(info.metadata) # XMP data to be embed
```

Is it as simple as changing the first line to:

```
from pyexiv2 import ImageData as TaggedImage
````

Unfortunately it still doesn't work for me...
